#  该配置文件是一个示例，具体的配置项和参数需要根据实际情况进行调整
#  mihomo 以及 sing-box 的配置示例在 example 需要根据实际情况进行调整
#  以下所有时间都是 Golang 的 Duration 格式
mihomo-api-url: http://127.0.0.1:59092
mihomo-api-token: test_token
mihomo-api-timeout: 5s
mihomo-group-latency-test: 自动回退 #自动回退的策略组名
mihomo-group-port-forward: 端口转发用 #端口转发的策略组名
checker: #测试使用的 URL 是 https://www.gstatic.com/generate_204 ，已固定在代码中
  proxy: http://127.0.0.1:7890
  timeout: 700ms #检测超时
  interval: 50ms #检测间隔
switcher:
  check-rise-interval: 10s #每隔 10s 检查主节点是否在线，如果在线则切换到主节点
connclose:
  listen-ip: 127.0.0.1
  listen-port: 9211
  #上面指定的是端口转发的地址，以辨别应该关闭哪个连接